; configuration typique pour un environnement de production:

;N'afficher SURTOUT PAS les erreurs
display_startup_errors = Off
display_errors = Off
;Rapporter toutes les erreurs SAUF les notice (pour ne pas polluer vos logs) ->->Fixe le niveau d'erreur
error_reporting = E_ALL & ~E_NOTICE
;Activer le log d'erreurs
log_errors = On



;Note: ensemble des directives PHP disponibles dans la documentation officielle de PHP:
;https://www.php.net/manual/fr/errorfunc.configuration.php