
userID
nomCheckedJS
prenomCheckedJS
email
telCheckedJS
adressCheckedJS
villeCheckedJS
codePostalCheckedJS
datePrestaCheckedJS
heurePrestaCheckedJS
menuCheckedJS
nbrPersCheckedJS
priceMenuCheckedJS
reductionRateCheckedJS
deliveryPriceCheckedJS
totalPriceCheckedJS
recordDeliveryDatas