; configuration type de système reporting, à l’aide de directives PHP,
;pour un environnement de développement sur un serveur

;Afficher les erreurs
display_startup_errors = On
display_errors = On
;Rapporter toutes les erreurs ->Fixe le niveau d'erreur
error_reporting = -1
;Activer le log d'erreurs
log_errors = On



;Note: ensemble des directives PHP disponibles dans la documentation officielle de PHP:
;https://www.php.net/manual/fr/errorfunc.configuration.php